Added the 'pipe' mechanism
aymericbouzy/react-replicate pull request #1
Opened 2017-03-22 16:46 UTC by jvdsande

Completed the Emitter and Receiver components to implement wanted functionality
Added a parent class system to have multiple Emitter/Receiver pairs

2017-03-22 17:26 UTC, aymericbouzy requested changes
Bravo ! Il y a juste quelques corrections à faire :)

2017-03-22 17:26 UTC, aymericbouzy commented on src/index.js
> + *  An instance of EmitterReceiver provides to Component classes, Emitter and
to -> two

2017-03-22 17:26 UTC, aymericbouzy commented on src/index.js
> +        // Check if the Emitter acutally has content
actually

2017-03-22 17:26 UTC, aymericbouzy commented on src/index.js
> +        if (child !== null && child !== undefined) {
code duplication

2017-03-22 17:26 UTC, aymericbouzy commented on src/index.js
> +          child = child.length ? child : [child]  // Convert into Array
code duplication

2017-03-22 22:01 UTC, jvdsande commented
Requested changes implemented + minor logic improvement in the EmitterReceiver class

2017-03-23 11:14 UTC, aymericbouzy approved these changes

2017-03-23 16:32 UTC, closed without merging